name: Test package

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # The "build" workflow
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted
        
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Build using docker
    - name: Build
      run: docker compose build amqp
    
    # Test using docker
    - name: Test
      run: docker compose up --abort-on-container-exit amqp
    
    # Clean up and delete created data
    - name: Clean up
      run: docker compose down -v
